openapi: 3.0.3

info:
  title: Online Bookstore API
  version: 0.0.1
paths:
  /books/all:
    get:
      description: Retrieve all available books in the store
      operationId: retrieveAssortmentOfBooks
      responses:
        '200':
          description: Successfully retrieved books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: number
        author:
          type: string
        title:
          type: string
        bookType:
          type: string
        basePrice:
          type: number
