openapi: 3.0.3

info:
  title: Online Bookstore API
  version: 0.0.1
paths:
  /books/all:
    get:
      description: Retrieve all available books in the store
      operationId: retrieveAssortmentOfBooks
      responses:
        '200':
          description: Successfully retrieved books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
  /books/order:
    post:
      description: Place an order of books by given IDs
      operationId: placeAnOrder
      parameters:
        - in: query
          name: bookIds
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        '200':
          description: Successfully placed order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: number
        author:
          type: string
        title:
          type: string
        bookType:
          type: string
        basePrice:
          type: number
    Order:
      type: object
      properties:
        totalBooks:
          type: number
        totalPrice:
          type: number
